version: '3'
services:
  bookstore:
    image: bookstore:1.0.0
    restart: unless-stopped
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py shell < createsuperuser.py &&
             python manage.py runserver 0.0.0.0:6030"
    container_name: bookstore
    ports:
      - 0.0.0.0:6030:6030
    depends_on:
      - elasticsearch
      - kafka
      - zookeeper
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.4.14
    hostname: zookeeper
    restart: always
    ports:
     - 2181:2181
    environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: bitnami/kafka:2.2.0
    restart: always
    ports:
     - 9092:9092
    depends_on:
     - zookeeper
    hostname: kafka
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kakfa:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - reindex.remote.whitelist=138.201.84.41:9200

    ports:
      - 9200:9200
      - 9300:9300
    restart: always
  kibana:
    container_name: kibana
    image: kibana:7.14.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always